/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 노트 생성
         * @description 새 노트를 생성합니다. 생성 시 항상 DRAFT(임시저장) 상태로 저장되며, 발행은 /publish 엔드포인트를 사용하세요.
         */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{noteId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 노트 신고
         * @description 특정 노트를 신고합니다. 같은 노트를 중복 신고할 수 없습니다. 사유가 OTHER일 경우 reasonDetail을 함께 입력하세요.
         */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 이메일, 비밀번호, 닉네임으로 신규 계정을 생성합니다.
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh Token으로 새로운 Access Token을 발급받습니다. 헤더에 Refresh-Token을 담아 요청하세요.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 로그인된 사용자를 로그아웃합니다. Refresh Token이 삭제됩니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일과 비밀번호로 로그인합니다. Access Token과 Refresh Token을 반환합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 노트 단건 조회
         * @description noteId로 특정 노트를 조회합니다. 공개 노트는 비로그인도 조회 가능하며, 비공개/임시저장 노트는 본인만 조회 가능합니다.
         */
        get: operations["getNote"];
        put?: never;
        post?: never;
        /**
         * 노트 삭제
         * @description 노트를 삭제합니다. 본인의 노트만 삭제 가능합니다.
         */
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        /**
         * 노트 수정
         * @description 노트 내용을 수정합니다. 본인의 노트만 수정 가능합니다.
         */
        patch: operations["updateNote"];
        trace?: never;
    };
    "/api/notes/{noteId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 노트 발행
         * @description DRAFT 상태의 노트를 PUBLISHED 상태로 변경합니다. 본인의 노트만 발행 가능합니다.
         */
        patch: operations["publishNote"];
        trace?: never;
    };
    "/api/notes/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공개 노트 피드 조회
         * @description 모든 유저의 공개(isPublic=true, PUBLISHED) 노트를 조회합니다.
         */
        get: operations["getPublicNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 노트 목록 조회
         * @description 내 노트 전체 또는 상태별로 조회합니다. status 파라미터 없으면 전체 조회, DRAFT 또는 PUBLISHED로 필터링 가능합니다.
         */
        get: operations["getMyNotes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flavors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 맛/향 제안 목록 조회
         * @description 노트 작성 시 taste, aroma 입력에 사용할 제안 목록을 반환합니다.
         */
        get: operations["getAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alcohols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카테고리별 술 목록
         * @description 카테고리로 술 목록을 조회합니다. 예: WHISKEY, WINE, BEER
         */
        get: operations["getByCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alcohols/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 술 단건 조회
         * @description 술 ID로 상세 정보를 조회합니다.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alcohols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 술 검색
         * @description 키워드로 술을 검색합니다. 영문명, 한글명, 별칭(AlcoholAlias)을 통합 검색합니다.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NoteCreateRequest: {
            /** Format: int64 */
            alcoholId: number;
            title?: string;
            tasteIds: number[];
            aromaIds: number[];
            pairing?: string;
            /** Format: double */
            rating: number;
            description?: string;
            /** Format: date */
            drankAt?: string;
            location?: string;
        };
        ApiResponseNoteResponse: {
            success?: boolean;
            data?: components["schemas"]["NoteResponse"];
            message?: string;
        };
        FlavorItem: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        NoteResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            alcoholId?: number;
            alcoholName?: string;
            alcoholNameKo?: string;
            title?: string;
            tastes?: components["schemas"]["FlavorItem"][];
            aromas?: components["schemas"]["FlavorItem"][];
            pairing?: string;
            /** Format: double */
            rating?: number;
            description?: string;
            isPublic?: boolean;
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
            /** Format: date */
            drankAt?: string;
            location?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ReportRequest: {
            /** @enum {string} */
            reason: "SPAM" | "INAPPROPRIATE" | "FALSE_INFO" | "OTHER";
            reasonDetail?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: Record<string, never>;
            message?: string;
        };
        SignUpRequest: {
            email?: string;
            password?: string;
            nickname?: string;
            /** Format: date */
            birthDate?: string;
        };
        ApiResponseTokenResponse: {
            success?: boolean;
            data?: components["schemas"]["TokenResponse"];
            message?: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        NoteUpdateRequest: {
            /** Format: int64 */
            alcoholId: number;
            title?: string;
            tasteIds: number[];
            aromaIds: number[];
            pairing?: string;
            /** Format: double */
            rating: number;
            description?: string;
            isPublic: boolean;
            /** Format: date */
            drankAt?: string;
            location?: string;
        };
        ApiResponseListNoteResponse: {
            success?: boolean;
            data?: components["schemas"]["NoteResponse"][];
            message?: string;
        };
        ApiResponseListFlavorSuggestionResponse: {
            success?: boolean;
            data?: components["schemas"]["FlavorSuggestionResponse"][];
            message?: string;
        };
        FlavorSuggestionResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        AlcoholResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            nameKo?: string;
            /** @enum {string} */
            category?: "WHISKEY" | "WINE" | "BEER" | "SOJU" | "MAKGEOLLI" | "SAKE" | "VODKA" | "GIN" | "RUM" | "TEQUILA" | "BRANDY" | "COCKTAIL" | "ETC";
            categoryKo?: string;
            origin?: string;
            region?: string;
            /** Format: int32 */
            vintage?: number;
            /** Format: double */
            abv?: number;
            description?: string;
        };
        ApiResponseListAlcoholResponse: {
            success?: boolean;
            data?: components["schemas"]["AlcoholResponse"][];
            message?: string;
        };
        ApiResponseAlcoholResponse: {
            success?: boolean;
            data?: components["schemas"]["AlcoholResponse"];
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoteResponse"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header: {
                "Refresh-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoteResponse"];
                };
            };
        };
    };
    deleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoteResponse"];
                };
            };
        };
    };
    publishNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoteResponse"];
                };
            };
        };
    };
    getPublicNotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListNoteResponse"];
                };
            };
        };
    };
    getMyNotes: {
        parameters: {
            query?: {
                status?: "DRAFT" | "PUBLISHED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListNoteResponse"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFlavorSuggestionResponse"];
                };
            };
        };
    };
    getByCategory: {
        parameters: {
            query: {
                category: "WHISKEY" | "WINE" | "BEER" | "SOJU" | "MAKGEOLLI" | "SAKE" | "VODKA" | "GIN" | "RUM" | "TEQUILA" | "BRANDY" | "COCKTAIL" | "ETC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAlcoholResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAlcoholResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAlcoholResponse"];
                };
            };
        };
    };
}
